server:
  port: ${PORT:8081}

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/product-db
    username: admin
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true
    plataform: postgresql
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true

    show_sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app:
  secrets:
    jwt: ${API_SECRET:YXV0aC1hcGktbWF0aGV1cy1wZXJpbg==}

  rabbitmq:
    exchange:
      product: product.topic

    routing-key:
      product-stock: product-stock.rounting-key
      sales-confirmation: sales-confirmation.rounting-key

    queue:
      product-stock: product-stock.queue
      sales-confirmation: sales-confirmation.queue